alias lb='cd ~/workspace/librato'

# AWS Credentials
#export AWS_ACCESS_KEY=
#export AWS_SECRET_KEY=
#export AMAZON_AWS_ID=

#export AMAZON_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
#export AMAZON_SECRET_ACCESS_KEY=$AWS_SECRET_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
